//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazilar
    {
        public int yazi_id { get; set; }
        public string baslik { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string metin { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> yazar_id { get; set; }
        public string ozet { get; set; }
        public string fotograf { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
